### ISSUE TITLE
Miscellaneous revisions to manuscript

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic#245]
See the notes in the response_to_reviews doc 

- [x] review identification of audience vis a vis comments of reviewer 1. 
- [x] explain to reviewer 1 that the use-cases reflect what we expect users to do.  
- [x] add a "see below" to driving directions response in regard to supporting non-expert users
- [x] check description of use case 4 vis a vis reviewer comments, revise appropriately (@LunaSare)
   - [x] explain (to reviewer) how case 4 relates to example
   - [x] revise manuscript to state that this example relates to use-case 4
   - [x] add lines of code to provide phylogenetic context to the example and on how the figure was generated.
- [x] address taxon limit of 10 issue.  first part is to make sure the ms is clear.  Then reply to reviewer.  
- [x] respond to "medicinal value" comment
- [x] check out VertLife and respond appropriately to reviewer comment (@bomeara)
- [x] address the comment that the portal does not have all the web services
- [x] address the issue of scaling metadata.  portal should describe DateLife and OT scaling
- [x] make example with screenshot to show metadata for a tree
- [x] make sure [taxon search issue](https://github.com/phylotastic/phylo_webservices/issues/75) is fixed, and explain this (@abusalehmdtayeen)
- [x] explain feature request for bibliography download
- [x] address underscore issue following [portal ticket](https://github.com/phylotastic/phylotastic-portal/issues/352)
- [x] address metadata issue following [portal ticket](https://github.com/phylotastic/phylotastic-portal/issues/355)
- [x] fix bib download [portal ticket](https://github.com/phylotastic/phylotastic-portal/issues/356)

**Comment by arlin** [comment]
@bomeara I added the citations and checked off the vertlife issue.  Also re-wrote the sentence a bit.
